// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Members
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faBrokeragesApprovals from '@/i18n/brokerages-approvals/fa.json';
import enBrokeragesApprovals from '@/i18n/brokerages-approvals/en.json';
import faBrokeragesAssociation from '@/i18n/brokerages-association/fa.json';
import enBrokeragesAssociation from '@/i18n/brokerages-association/en.json';
import faBrokeragesBoardCommittees from '@/i18n/brokerages-board-committees/fa.json';
import enBrokeragesBoardCommittees from '@/i18n/brokerages-board-committees/en.json';
import faBrokeragesCommon from '@/i18n/brokerages-common/fa.json';
import enBrokeragesCommon from '@/i18n/brokerages-common/en.json';
import faBrokeragesCompanySoftware from '@/i18n/brokerages-company-software/fa.json';
import enBrokeragesCompanySoftware from '@/i18n/brokerages-company-software/en.json';
import faBrokeragesFinancialInfo from '@/i18n/brokerages-financial-info/fa.json';
import enBrokeragesFinancialInfo from '@/i18n/brokerages-financial-info/en.json';
import faBrokeragesFinancialInfoGuide from '@/i18n/brokerages-financial-info-guide/fa.json';
import enBrokeragesFinancialInfoGuide from '@/i18n/brokerages-financial-info-guide/en.json';
import faBrokeragesGeneralInfo from '@/i18n/brokerages-general-info/fa.json';
import enBrokeragesGeneralInfo from '@/i18n/brokerages-general-info/en.json';
import faBrokeragesGeneralInfoGuide from '@/i18n/brokerages-general-info-guide/fa.json';
import enBrokeragesGeneralInfoGuide from '@/i18n/brokerages-general-info-guide/en.json';
import faBrokeragesLegalCases from '@/i18n/brokerages-legal-cases/fa.json';
import enBrokeragesLegalCases from '@/i18n/brokerages-legal-cases/en.json';
import faBrokeragesLicenses from '@/i18n/brokerages-licenses/fa.json';
import enBrokeragesLicenses from '@/i18n/brokerages-licenses/en.json';
import faBrokeragesMembersInfo from '@/i18n/brokerages-members-info/fa.json';
import enBrokeragesMembersInfo from '@/i18n/brokerages-members-info/en.json';
import faBrokeragesTradingOffices from '@/i18n/brokerages-trading-offices/fa.json';
import enBrokeragesTradingOffices from '@/i18n/brokerages-trading-offices/en.json';
import faBrokeragesTradingOfficesGuide from '@/i18n/brokerages-trading-offices-guide/fa.json';
import enBrokeragesTradingOfficesGuide from '@/i18n/brokerages-trading-offices-guide/en.json';
import faBrokeragesTradingStations from '@/i18n/brokerages-trading-stations/fa.json';
import enBrokeragesTradingStations from '@/i18n/brokerages-trading-stations/en.json';
import faBrokeragesTradingStationsGuide from '@/i18n/brokerages-trading-stations-guide/fa.json';
import enBrokeragesTradingStationsGuide from '@/i18n/brokerages-trading-stations-guide/en.json';
import faCompanyDocument from '@/i18n/company-document/fa.json';
import enCompanyDocument from '@/i18n/company-document/en.json';
import faCompanyInformation from '@/i18n/company-information/fa.json';
import enCompanyInformation from '@/i18n/company-information/en.json';
import faCompanyInformationGuide from '@/i18n/company-information-guide/fa.json';
import enCompanyInformationGuide from '@/i18n/company-information-guide/en.json';
import faInvestmentFunds from '@/i18n/investment-funds/fa.json';
import enInvestmentFunds from '@/i18n/investment-funds/en.json';
import faMembers from '@/i18n/members/fa.json';
import enMembers from '@/i18n/members/en.json';
import faMembersReports from '@/i18n/members-reports/fa.json';
import enMembersReports from '@/i18n/members-reports/en.json';
import faPersonAccess from '@/i18n/person-access/fa.json';
import enPersonAccess from '@/i18n/person-access/en.json';
import faPersonAddress from '@/i18n/person-address/fa.json';
import enPersonAddress from '@/i18n/person-address/en.json';
import faPersonAsset from '@/i18n/person-asset/fa.json';
import enPersonAsset from '@/i18n/person-asset/en.json';
import faPersonContact from '@/i18n/person-contact/fa.json';
import enPersonContact from '@/i18n/person-contact/en.json';
import faPersonDocument from '@/i18n/person-document/fa.json';
import enPersonDocument from '@/i18n/person-document/en.json';
import faPersonEducation from '@/i18n/person-education/fa.json';
import enPersonEducation from '@/i18n/person-education/en.json';
import faPersonEmployment from '@/i18n/person-employment/fa.json';
import enPersonEmployment from '@/i18n/person-employment/en.json';
import faPersonForm from '@/i18n/person-form/fa.json';
import enPersonForm from '@/i18n/person-form/en.json';
import faPersonNameGrid from '@/i18n/person-name-grid/fa.json';
import enPersonNameGrid from '@/i18n/person-name-grid/en.json';
import faPersonNationality from '@/i18n/person-nationality/fa.json';
import enPersonNationality from '@/i18n/person-nationality/en.json';
import faPersonProfessionalTraining from '@/i18n/person-professional-training/fa.json';
import enPersonProfessionalTraining from '@/i18n/person-professional-training/en.json';
import faPersonRelationship from '@/i18n/person-relationship/fa.json';
import enPersonRelationship from '@/i18n/person-relationship/en.json';
import faPersonSearch from '@/i18n/person-search/fa.json';
import enPersonSearch from '@/i18n/person-search/en.json';
import faPersonSidebar from '@/i18n/person-sidebar/fa.json';
import enPersonSidebar from '@/i18n/person-sidebar/en.json';
import faPersonStatus from '@/i18n/person-status/fa.json';
import enPersonStatus from '@/i18n/person-status/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'brokerages-approvals': faBrokeragesApprovals,
  'brokerages-association': faBrokeragesAssociation,
  'brokerages-board-committees': faBrokeragesBoardCommittees,
  'brokerages-common': faBrokeragesCommon,
  'brokerages-company-software': faBrokeragesCompanySoftware,
  'brokerages-financial-info': faBrokeragesFinancialInfo,
  'brokerages-financial-info-guide': faBrokeragesFinancialInfoGuide,
  'brokerages-general-info': faBrokeragesGeneralInfo,
  'brokerages-general-info-guide': faBrokeragesGeneralInfoGuide,
  'brokerages-legal-cases': faBrokeragesLegalCases,
  'brokerages-licenses': faBrokeragesLicenses,
  'brokerages-members-info': faBrokeragesMembersInfo,
  'brokerages-trading-offices': faBrokeragesTradingOffices,
  'brokerages-trading-offices-guide': faBrokeragesTradingOfficesGuide,
  'brokerages-trading-stations': faBrokeragesTradingStations,
  'brokerages-trading-stations-guide': faBrokeragesTradingStationsGuide,
  'company-document': faCompanyDocument,
  'company-information': faCompanyInformation,
  'company-information-guide': faCompanyInformationGuide,
  'investment-funds': faInvestmentFunds,
  'members': faMembers,
  'members-reports': faMembersReports,
  'person-access': faPersonAccess,
  'person-address': faPersonAddress,
  'person-asset': faPersonAsset,
  'person-contact': faPersonContact,
  'person-document': faPersonDocument,
  'person-education': faPersonEducation,
  'person-employment': faPersonEmployment,
  'person-form': faPersonForm,
  'person-name-grid': faPersonNameGrid,
  'person-nationality': faPersonNationality,
  'person-professional-training': faPersonProfessionalTraining,
  'person-relationship': faPersonRelationship,
  'person-search': faPersonSearch,
  'person-sidebar': faPersonSidebar,
  'person-status': faPersonStatus,
  },
  en: {
  'brokerages-approvals': enBrokeragesApprovals,
  'brokerages-association': enBrokeragesAssociation,
  'brokerages-board-committees': enBrokeragesBoardCommittees,
  'brokerages-common': enBrokeragesCommon,
  'brokerages-company-software': enBrokeragesCompanySoftware,
  'brokerages-financial-info': enBrokeragesFinancialInfo,
  'brokerages-financial-info-guide': enBrokeragesFinancialInfoGuide,
  'brokerages-general-info': enBrokeragesGeneralInfo,
  'brokerages-general-info-guide': enBrokeragesGeneralInfoGuide,
  'brokerages-legal-cases': enBrokeragesLegalCases,
  'brokerages-licenses': enBrokeragesLicenses,
  'brokerages-members-info': enBrokeragesMembersInfo,
  'brokerages-trading-offices': enBrokeragesTradingOffices,
  'brokerages-trading-offices-guide': enBrokeragesTradingOfficesGuide,
  'brokerages-trading-stations': enBrokeragesTradingStations,
  'brokerages-trading-stations-guide': enBrokeragesTradingStationsGuide,
  'company-document': enCompanyDocument,
  'company-information': enCompanyInformation,
  'company-information-guide': enCompanyInformationGuide,
  'investment-funds': enInvestmentFunds,
  'members': enMembers,
  'members-reports': enMembersReports,
  'person-access': enPersonAccess,
  'person-address': enPersonAddress,
  'person-asset': enPersonAsset,
  'person-contact': enPersonContact,
  'person-document': enPersonDocument,
  'person-education': enPersonEducation,
  'person-employment': enPersonEmployment,
  'person-form': enPersonForm,
  'person-name-grid': enPersonNameGrid,
  'person-nationality': enPersonNationality,
  'person-professional-training': enPersonProfessionalTraining,
  'person-relationship': enPersonRelationship,
  'person-search': enPersonSearch,
  'person-sidebar': enPersonSidebar,
  'person-status': enPersonStatus,
  },
} as const;
